#!/usr/bin/env python3
"""
Templeman Opticians — Outreach Dashboard Generator
Produces an HTML dashboard showing the full pipeline
"""
import sqlite3
from datetime import datetime

DB = "/Users/nicholas/care-homes-essex.db"

def dashboard_html():
    conn = sqlite3.connect(DB)
    c = conn.cursor()
    
    c.execute("""SELECT stage, COUNT(*), SUM(value), 
        ROUND(SUM(value * probability / 100.0)) 
        FROM pipeline GROUP BY stage ORDER BY SUM(value) DESC""")
    stages = c.fetchall()
    
    c.execute("""SELECT ch.name, ch.location, ch.residents, ch.rating, p.value, 
        p.probability, ROUND(p.value * p.probability / 100.0) as weighted,
        ch.contact, ch.email, ch.phone
        FROM care_homes ch JOIN pipeline p ON ch.id = p.care_home_id 
        WHERE p.stage = 'prospect' ORDER BY p.value DESC LIMIT 10""")
    top = c.fetchall()
    
    c.execute("SELECT COUNT(*), SUM(residents) FROM care_homes WHERE contacted=0")
    uncontacted = c.fetchone()
    
    total_value = sum(s[2] for s in stages)
    total_weighted = sum(s[3] for s in stages)
    
    html = f"""<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>Templeman Outreach Dashboard</title>
<style>
body{{font-family:Inter,-apple-system,sans-serif;background:#f8f4ee;padding:2rem}}
h1{{font-size:2rem;margin-bottom:.5rem}}
.stats{{display:flex;gap:1rem;flex-wrap:wrap;margin:1.5rem 0}}
.stat{{background:#fff;padding:1.2rem;border-radius:12px;min-width:140px;text-align:center;box-shadow:0 2px 8px rgba(0,0,0,.05)}}
.stat .num{{font-size:2rem;font-weight:700;color:#c4a23a}}
.stat .label{{font-size:.8rem;color:#888;margin-top:.3rem}}
table{{width:100%;background:#fff;border-radius:12px;overflow:hidden;box-shadow:0 2px 8px rgba(0,0,0,.05);margin:1rem 0}}
th{{background:#0f0f1a;color:#fff;padding:.6rem .8rem;text-align:left;font-size:.85rem}}
td{{padding:.6rem .8rem;border-bottom:1px solid #eee;font-size:.9rem}}
.good{{color:#2d5a3b;font-weight:600}}
.outstanding{{color:#c4a23a;font-weight:700}}
.cta{{display:inline-block;background:#c4a23a;color:#0f0f1a;padding:.5rem 1rem;border-radius:8px;text-decoration:none;font-weight:700;margin:.3rem}}
</style></head><body>
<h1>📊 Templeman Opticians — Outreach Dashboard</h1>
<p>{datetime.now().strftime('%d %B %Y %H:%M')} | 30 care homes | {uncontacted[1]} residents</p>

<div class="stats">
<div class="stat"><div class="num">£{total_value:,}</div><div class="label">Total Pipeline</div></div>
<div class="stat"><div class="num">£{int(total_weighted):,}</div><div class="label">Weighted (20%)</div></div>
<div class="stat"><div class="num">£{int(total_value*0.3):,}</div><div class="label">Target (30%)</div></div>
<div class="stat"><div class="num">£{int(total_value*0.3/12):,}/mo</div><div class="label">MRR Target</div></div>
<div class="stat"><div class="num">{uncontacted[0]}</div><div class="label">To Contact</div></div>
</div>

<h2>Pipeline Stages</h2>
<table>
<tr><th>Stage</th><th>Homes</th><th>Value</th><th>Weighted</th></tr>
{"".join(f'<tr><td>{s[0]}</td><td>{s[1]}</td><td>£{s[2]:,}</td><td>£{int(s[3]):,}</td></tr>' for s in stages)}
</table>

<h2>Top 10 Prospects</h2>
<table>
<tr><th>Care Home</th><th>Location</th><th>Beds</th><th>Rating</th><th>Value</th><th>Prob</th><th>Weighted</th><th>Contact</th></tr>
{"".join(f'<tr><td><strong>{r[0]}</strong></td><td>{r[1]}</td><td>{r[2]}</td><td class="{"outstanding" if r[3]=="Outstanding" else "good" if r[3]=="Good" else ""}">{r[3]}</td><td>£{r[4]:,}</td><td>{r[5]}%</td><td>£{int(r[6]):,}</td><td>{r[7]}<br><small>{r[8]}</small></td></tr>' for r in top)}
</table>

<p style="margin-top:1rem">
<a href="/" class="cta">← Templeman Opticians</a>
<a href="/book-home-test" class="cta">Book Home Test</a>
</p>

<p style="color:#888;font-size:.8rem;margin-top:2rem">Auto-generated by Outreach Controller · templeman-opticians.com</p>
</body></html>"""
    return html

if __name__ == "__main__":
    with open("/Users/nicholas/clawd/templeman-opticians-site/dashboard.html", "w") as f:
        f.write(dashboard_html())
    print("Dashboard written to templeman-opticians-site/dashboard.html")
    print(f"Total pipeline: £{sum(1 for _ in open('/dev/null')):,}") # placeholder
    
    # Also print summary
    conn = sqlite3.connect(DB)
    c = conn.cursor()
    c.execute("SELECT SUM(value), COUNT(*) FROM pipeline")
    total, count = c.fetchone()
    print(f"Pipeline: {count} homes | £{total:,} total | £{int(total*0.3/12):,}/mo MRR target")
