#!/usr/bin/env bash
# Smoke tests for all 7 services. Asserts each endpoint returns 200
# and a sane response shape. Exits non-zero on first failure.
set -euo pipefail

BASE="${BASE:-http://localhost}"

pass=0
fail=0

check() {
  local name="$1"
  local url="$2"
  local pattern="$3"
  local body
  body="$(curl -sf --max-time 5 "$url" || true)"
  if [[ "$body" == *"$pattern"* ]]; then
    printf "  ✓ %-25s %s\n" "$name" "$url"
    pass=$((pass+1))
  else
    printf "  ✗ %-25s %s\n     expected: %s\n     got:      %s\n" "$name" "$url" "$pattern" "${body:0:120}"
    fail=$((fail+1))
  fi
}

echo "━━━ openpatent.ai hive — smoke tests ━━━"
echo ""

# 1. patentmcp core
check "patentmcp /health"        "$BASE:3210/health"          '"status": "OK"'
check "patentmcp /stats"         "$BASE:3210/stats"           '"system": "PatentMCP"'

# 2. API gateway
check "api-gateway /"            "$BASE:3211/"                '"tagline"'
check "api-gateway /pricing"     "$BASE:3211/pricing"         '"defensive"'
check "api-gateway /legal"       "$BASE:3211/legal"           '"eidas"'
check "api-gateway /mcp.json"    "$BASE:3211/.well-known/mcp.json" '"openpatent-mcp"'

# 3. Worker
check "worker /health"           "$BASE:3212/health"          '"status": "OK"'

# 4. BFT council
check "bft /health"              "$BASE:3215/health"          '"status": "OK"'
check "bft /agents"              "$BASE:3215/agents"          '"council_size"'

# 5. Verify page
check "verify /"                 "$BASE:3213/"                'verify.openpatent.ai'

# 6. MCP manifest
check "mcp /"                    "$BASE:3214/.well-known/mcp.json" '"disclose_invention"'
check "mcp /tools"               "$BASE:3214/tools"           '"disclose_invention"'

# 7. Landing
check "landing /"                "$BASE:3000/"                'Disclose First'

# 8. End-to-end: POST a disclosure via the gateway
echo ""
echo "━━━ end-to-end: full disclosure flow ━━━"
DOC_B64="$(echo -n 'Invention disclosure test from hive smoke test.' | base64)"
DISCLOSURE_RESPONSE="$(curl -sf --max-time 15 -X POST "$BASE:3211/v1/disclosure" \
  -H 'Content-Type: application/json' \
  -d "{\"title\":\"Hive Smoke Test\",\"description\":\"Generated by bring-up smoke test.\",\"inventor_did\":\"did:key:z6MkiSmTest\",\"document_base64\":\"$DOC_B64\",\"tier\":\"defensive\"}" \
  || true)"

if [[ "$DISCLOSURE_RESPONSE" == *'"status": "DISCLOSED"'* ]]; then
  echo "  ✓ POST /v1/disclosure returned DISCLOSED"
  pass=$((pass+1))
  # Extract attestation URL
  ATT_URL="$(echo "$DISCLOSURE_RESPONSE" | python3 -c 'import sys,json; d=json.load(sys.stdin); print(d.get("attestation_url",""))')"
  echo "    attestation: $ATT_URL"
  # Extract hash
  HASH="$(echo "$DISCLOSURE_RESPONSE" | python3 -c 'import sys,json; d=json.load(sys.stdin); print(d.get("document_hash","")[:16])')"
  echo "    hash prefix: $HASH"
else
  echo "  ✗ POST /v1/disclosure failed"
  echo "    response: ${DISCLOSURE_RESPONSE:0:300}"
  fail=$((fail+1))
fi

echo ""
echo "━━━ results ━━━"
echo "  passed: $pass"
echo "  failed: $fail"
[ "$fail" -eq 0 ]
