#!/usr/bin/env python3
"""Live health + AEO/SEO/GEO readiness check for all empire deploy directories."""
import os
import re
import html
import urllib.request
import urllib.error
from pathlib import Path
from concurrent.futures import ThreadPoolExecutor, as_completed
from datetime import datetime

BASE = Path("/Users/nicholas/clawd")
REPORT = BASE / "_findings" / "EMPIRE_HEALTH_CHECK_2026-06-15.md"
TIMEOUT = 15
MAX_WORKERS = 8


def extract_canonical(text: str) -> str:
    m = re.search(r'<link[^>]+rel=["\']canonical["\'][^>]+href=["\']([^"\']+)["\']', text, re.I)
    if not m:
        m = re.search(r'<link[^>]+href=["\']([^"\']+)["\'][^>]+rel=["\']canonical["\']', text, re.I)
    return m.group(1).strip() if m else ""


def derive_url(dir_name: str, canonical: str) -> str:
    if canonical:
        return canonical.replace("http://", "https://", 1)
    slug = dir_name.replace("-deploy", "")
    return f"https://{slug}-deploy.vercel.app"


def check(url: str) -> int:
    try:
        req = urllib.request.Request(url, headers={"User-Agent": "MEOK-HealthBot/1.0"}, method="GET")
        with urllib.request.urlopen(req, timeout=TIMEOUT) as resp:
            return resp.getcode()
    except urllib.error.HTTPError as e:
        return e.code
    except Exception:
        return 0


def grade(status: int, has_llms: bool, has_robots: bool, has_sitemap: bool, has_meta: bool) -> str:
    if status != 200:
        return "F"
    if has_llms and has_robots and has_sitemap and has_meta:
        return "A"
    if has_robots and (has_llms or has_sitemap) and has_meta:
        return "B"
    if has_robots and has_meta:
        return "C"
    if status == 200:
        return "D"
    return "F"


def has_meta_og(text: str) -> bool:
    return bool(re.search(r'<meta[^>]+property=["\']og:title["\']', text, re.I) or re.search(r'<meta[^>]+name=["\']description["\']', text, re.I))


def process_dir(deploy_dir: Path) -> dict:
    index = deploy_dir / "index.html"
    if not index.exists():
        return None
    text = index.read_text(encoding="utf-8", errors="ignore")
    canonical = extract_canonical(text)
    url = derive_url(deploy_dir.name, canonical)
    status = check(url)
    has_meta = has_meta_og(text)
    llms = check(url.rstrip("/") + "/llms.txt") if status == 200 else 0
    robots = check(url.rstrip("/") + "/robots.txt") if status == 200 else 0
    sitemap = check(url.rstrip("/") + "/sitemap.xml") if status == 200 else 0
    openapi = check(url.rstrip("/") + "/openapi.json") if status == 200 else 0
    return {
        "dir": deploy_dir.name,
        "url": url,
        "status": status,
        "llms": llms,
        "robots": robots,
        "sitemap": sitemap,
        "openapi": openapi,
        "meta": has_meta,
        "grade": grade(status, llms == 200, robots == 200, sitemap == 200, has_meta),
    }


def code_cell(code: int) -> str:
    if code == 200:
        return "✅ 200"
    if code == 0:
        return "❌ ERR"
    return f"🔴 {code}"


def main():
    dirs = [d for d in sorted(BASE.glob("*-deploy")) if d.is_dir()]
    results = []
    with ThreadPoolExecutor(max_workers=MAX_WORKERS) as ex:
        futures = {ex.submit(process_dir, d): d for d in dirs}
        for f in as_completed(futures):
            res = f.result()
            if res:
                results.append(res)
    results.sort(key=lambda r: (r["grade"], r["dir"]))

    grades = {"A": 0, "B": 0, "C": 0, "D": 0, "F": 0}
    for r in results:
        grades[r["grade"]] += 1

    lines = [
        "# Empire Health + AEO/GEO/SEO Readiness Check — 2026-06-15",
        f"**Generated:** {datetime.utcnow().isoformat()}Z",
        f"**Directories scanned:** {len(results)}",
        "",
        "## Grade Distribution",
        "",
        f"- **A:** {grades['A']}",
        f"- **B:** {grades['B']}",
        f"- **C:** {grades['C']}",
        f"- **D:** {grades['D']}",
        f"- **F:** {grades['F']}",
        "",
        "## Detailed Results",
        "",
        "| Directory | URL | HTTP | llms.txt | robots.txt | sitemap.xml | openapi.json | Meta/OG | Grade |",
        "|---|---|---|---|---|---|---|---|---|",
    ]
    for r in results:
        lines.append(
            f"| {r['dir']} | {r['url']} | {code_cell(r['status'])} | {code_cell(r['llms'])} | {code_cell(r['robots'])} | {code_cell(r['sitemap'])} | {code_cell(r['openapi'])} | {'✅' if r['meta'] else '❌'} | {r['grade']} |"
        )
    lines += ["", "---", "*Generated by clawd/scripts/empire-health-check.py*", ""]
    REPORT.parent.mkdir(parents=True, exist_ok=True)
    REPORT.write_text("\n".join(lines), encoding="utf-8")
    print(f"Scanned {len(results)} directories.")
    print(f"Grades: {grades}")
    print(f"Report: {REPORT}")


if __name__ == "__main__":
    main()
