#!/bin/bash
# Hermes daily governance content publisher
# Cron: 0 9 * * * (9 AM UTC — publishes content based on overnight learning)
# Writes a draft governance blog post to meok.ai/blog based on the day's intel

set -e
CORPUS=~/.hermes/governance-corpus
DRAFTS=~/.hermes/blog-drafts
mkdir -p "$DRAFTS" ~/.hermes/logs
LOG=~/.hermes/logs/content-publish.log
DATE=$(date -u +%Y-%m-%d)

echo "===== $(date -u +%Y-%m-%dT%H:%M:%SZ) — Content Drafting =====" >> "$LOG"

# Pull today's signals from yesterday's learning logs
EURLEX_NEW=$(tail -100 ~/.hermes/logs/governance-learn.log 2>/dev/null | grep -A1 "EUR-Lex" | grep -v "^--" | grep -v "^$" | head -3)
CISA_NEW=$(tail -100 ~/.hermes/logs/governance-learn.log 2>/dev/null | grep -A5 "CISA KEV" | grep "CVE" | head -3)
INDUSTRY_NEW=$(tail -200 ~/.hermes/logs/industry-news.log 2>/dev/null | grep "•" | head -5)

DRAFT_FILE="$DRAFTS/$DATE-governance-digest.md"

cat > "$DRAFT_FILE" <<EOF
---
title: "EU AI Act + Regulation Digest — ${DATE}"
date: ${DATE}
description: "Daily AI governance + cybersecurity intelligence from MEOK AI Labs"
category: governance
status: draft
---

# Governance Digest: ${DATE}

## What changed in EU regulation
${EURLEX_NEW:-(no updates today)}

## Critical vulnerabilities added to CISA KEV
${CISA_NEW:-(no critical additions today)}

## Industry regulator news
${INDUSTRY_NEW:-(no major regulator news)}

## What this means for compliance teams
[Hermes auto-draft — Nick edits before publish]

## MEOK MCPs that help
- \`eu-ai-act-compliance-mcp\` — search 410 articles of regulation text via FTS5
- \`cisa-kev-mcp\` — query Known Exploited Vulnerabilities catalogue
- \`agent-audit-logger-mcp\` — immutable A2A audit trail for governance evidence

\`\`\`bash
pip install eu-ai-act-compliance-mcp cisa-kev-mcp agent-audit-logger-mcp
\`\`\`

---
*Generated by Hermes governance daily learner. Edit and publish at meok.ai/blog.*
EOF

echo "Draft written: $DRAFT_FILE ($(wc -l < "$DRAFT_FILE") lines)" >> "$LOG"
echo "" >> "$LOG"
